### ISSUE TITLE
[BUG]: ScoreBoard存在网络跑主线程

### ISSUE THREAD

**Issue by Birditch** [FloraCore/FloraCore#16]
### 联系方式

bilibili.mer@outlook.com

### 简明扼要地描述该错误是什么

getOfflinePlayer是会主线程访问网络的。

### FloraCore版本

2.0.15.3

### 服务器类型

Paper/Bukkit

### 复现步骤

无

### 堆栈错误日志

```shell
at team.floracore.bukkit.scoreboard.core.SidebarBoardPage$BoardLine.<init>(SidebarBoardPage.java:125)
at team.floracore.bukkit.scoreboard.core.SidebarBoardPage.<init>(SidebarBoardPage.java:56)
at team.floracore.bukkit.scoreboard.core.SidebarBoard.newPage(SidebarBoard.java:21)
at team.floracore.bukkit.scoreboard.core.SidebarBoard.newPage(SidebarBoard.java:14)
at team.floracore.bukkit.scoreboard.core.Board.addTarget(Board.java:33)
at team.floracore.bukkit.scoreboard.ScoreBoardManager.lambda$addTarget$2(ScoreBoardManager.java:65)
at team.floracore.bukkit.scoreboard.ScoreBoardManager$$Lambda$3113/0x00000001013e7040.run(Unknown Source)
```

### 用户协议

- [X] 我同意遵守FloraCore的用户协议。

**Comment by Birditch** [comment]
https://github.com/FloraCore/FloraCore/commit/6d5a512c648fb85ec6be802f827485638a21470b 已删除ScoreBoard功能，建议使用其他更好的插件代替。

**Comment by SnowballXueQiu** [comment]
@xLikeWATCHDOG 为什么把tab插件融进来

**Comment by Birditch** [comment]
@SnowballXueQiu 什么时候把tab插件融进来了？
