### ISSUE TITLE
PARTY错误

### ISSUE THREAD

**Issue by xLikeWATCHDOG** [FloraCore/FloraCore#4]
在最新的一次编译中，我们进行了跨服测试。
遗憾的是，跨服测试全线崩溃。
[2023-05-18-7.log.gz](https://github.com/FloraCore/FloraCore/files/11508844/2023-05-18-7.log.gz)
当玩家在其它服务器向这名玩家发送邀请时，我们发现，被邀请的玩家服务器会出现如下报错。
```
[22:59:09] [floracore-worker-2/WARN]: [FloraCore] Unable to decode incoming messaging service message: '{"id":"24ad01c7-6989-4f04-840c-bb147de8c152","type":"notice","content":{"receiver":"889dcaa5-928a-37e4-9220-e2da97df0d9b","type":"PARTY_ACCEPT","parameters":"[dda915f8-abf6-31e8-8221-e0eaa1f9c4c7, 06954e51-dfc9-46cc-bb1f-c27de7ae05c7]"}}'
java.lang.NumberFormatException: For input string: "[dda915f8"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_342]
	at java.lang.Long.parseLong(Long.java:589) ~[?:1.8.0_342]
	at java.lang.Long.valueOf(Long.java:776) ~[?:1.8.0_342]
	at java.lang.Long.decode(Long.java:928) ~[?:1.8.0_342]
	at java.util.UUID.fromString(UUID.java:198) ~[?:1.8.0_342]
	at team.floracore.common.messaging.FloraCoreMessagingService.notice(FloraCoreMessagingService.java:258) ~[floracore-jarinjar3138569875078408887.jar.tmp:?]
	at team.floracore.common.messaging.FloraCoreMessagingService.processIncomingMessage(FloraCoreMessagingService.java:406) ~[floracore-jarinjar3138569875078408887.jar.tmp:?]
	at team.floracore.common.messaging.FloraCoreMessagingService.consumeIncomingMessageAsString0(FloraCoreMessagingService.java:383) ~[floracore-jarinjar3138569875078408887.jar.tmp:?]
	at team.floracore.common.messaging.FloraCoreMessagingService.consumeIncomingMessageAsString(FloraCoreMessagingService.java:328) [floracore-jarinjar3138569875078408887.jar.tmp:?]
	at team.floracore.common.messaging.redis.RedisMessenger$Subscription.onMessage(RedisMessenger.java:93) [floracore-jarinjar3138569875078408887.jar.tmp:?]
	at team.floracore.lib.jedis.JedisPubSub.process(JedisPubSub.java:156) [jedis-4.3.1-remapped.jar:?]
	at team.floracore.lib.jedis.JedisPubSub.proceed(JedisPubSub.java:125) [jedis-4.3.1-remapped.jar:?]
	at team.floracore.lib.jedis.Jedis.subscribe(Jedis.java:7908) [jedis-4.3.1-remapped.jar:?]
	at team.floracore.common.messaging.redis.RedisMessenger$Subscription.run(RedisMessenger.java:68) [floracore-jarinjar3138569875078408887.jar.tmp:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [?:1.8.0_342]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_342]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_342]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_342]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_342]
```
同时，我们还进行了跨服聊天频道测试。
同样，在跨服测试中，这不起作用。但是在同个服务器测试中，它却很好的起了作用。
我们认为，使用相同技术原理的Rreport通知也受到了影响。
应当在后续的版本中着重注重跨服的适配性，这是最不可缺少的。也是FC的生命力所在。

**Comment by flowerinsnowdh** [comment]
# 版本问题
我不知道出现该异常的commit是哪一个commit，请把对应的提交记录贴上来

# 问题分析
尽管暂时不知道问题出现位置，但是这个异常无论在哪个提交中都是因为`FloraCoreMessagingService`这个类在处理redis消息时，调用`UUID.fromString(String)`时抛出的，也如上方所看到，异常是

```console
java.lang.NumberFormatException: For input string: "[dda915f8"
```

是UUID解析失败的问题，看起来`[dda915f8`这个解析内容只有一小段，我的猜想是redis消息格式错误，你是否尝试过将redis频道消息打印到控制台？

**Comment by xLikeWATCHDOG** [comment]
该问题已于提交
https://github.com/FloraCore/FloraCore/commit/e1e5833fd5ba9a433b5e1c5efabe2a0b0b010d85
解决

**Comment by xLikeWATCHDOG** [comment]
### 解决方法：
将String[]改成了List<String>，调用Gson，将其格式化为json。
处理时，再由数组json转化为List<String>解决方法和[https://github.com/FloraCore/FloraCore/issues/4#issuecomment-1553315354](url)所说差不多，似乎我这个解决方法还更加复杂了。
但通过了测试。
也不做修改了。
