### ISSUE TITLE
[BUG]: 组队邀请不存在的玩家会抛出NPE

### ISSUE THREAD

**Issue by xLikeWATCHDOG** [FloraCore/FloraCore#9]
### 联系方式

bilibili.mer@outlook.com

### 简明扼要地描述该错误是什么

如题
因为过段时间我就不在了，所以发布此议题。
如果我没修复，我就会挂着，如果我修复了，那这个议题就会没了。
然后如果我没修复，那后续的开发者嘎嘎修复！
栓q

### FloraCore版本

2.0.4.8

### 服务器类型

BungeeCord

### 复现步骤

如题

### 堆栈错误日志

```shell
[18:59:01 INFO]: test executed command: /p DaddyBaymax
[18:59:01 ERROR] [FloraCore]: Exception executing command handler
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_342]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:1979) ~[?:?]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:1953) ~[?:?]
        at com.github.benmanes.caffeine.cache.LocalManualCache.put(LocalManualCache.java:130) ~[?:?]
        at team.floracore.common.api.implementation.ApiPlayer.getPlayers(ApiPlayer.java:34) ~[?:?]
        at team.floracore.common.api.implementation.ApiPlayer.getPlayerRecordUUID(ApiPlayer.java:41) ~[?:?]
        at team.floracore.bungee.commands.socialsystems.PartyCommand.invite1(PartyCommand.java:86) ~[?:?]
        at team.floracore.bungee.commands.socialsystems.PartyCommand.invite(PartyCommand.java:46) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_342]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:649) ~[?:1.8.0_342]
        at cloud.commandframework.annotations.MethodCommandExecutionHandler.execute(MethodCommandExecutionHandler.java:79) ~[?:?]
        at cloud.commandframework.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95) ~[?:?]
        at cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123) ~[?:?]
        at cloud.commandframework.CommandManager.executeCommand(CommandManager.java:189) ~[?:?]
        at cloud.commandframework.bungee.BungeeCommand.execute(BungeeCommand.java:77) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:213) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:164) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at net.md_5.bungee.connection.UpstreamBridge.handleChat(UpstreamBridge.java:212) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:167) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:71) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_342]
```

### 用户协议

- [X] 我同意遵守FloraCore的用户协议。

**Comment by xLikeWATCHDOG** [comment]
我在目标报错位置加了个判断。
```
        if (player == null) {
            player = plugin.getStorage().getImplementation().selectPlayer(name);
            if (player == null){
                return null;
            }
            playerRecordCache.put(name, player);
        }
```
这个似乎表明了，缓存的值不能是null。
这个是可能的解决方法。

**Comment by xLikeWATCHDOG** [comment]
通过上述方法，确实可行，已解决。
